language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "4"
install: npm install
before_install: 
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@3; fi
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success: ".travis/ci-release.jsh"
env:
  global:
  - secure: "Bdlddvmo/Edm5Il21e0c1ivzA9GR7wZCyZinGJNXxXVD41blefmCLTyfahLT5dgtnqFabFgDUAeDM5VQS88nIDakzql47DD9J7xkjkIlr8B0J9L3DthUrV6Z1IZE/tp0Lq8ttpbgo0KakNqrQ7w7N2QyZqPIw64KsRXTiV/fCPYoa0cLEkWkF1WKHMhZDh6x8m9j4y0n3GIhuu6zNgSGvCv3cJdiIeQ4VzyTnIyQXikpmvGNldU8kJHwxwdHnOtycMWP8o6OX9vY4fJ+OQlcw6B8kfSzoDk0M8ED4TwDK984mhNUJFOfIyGJZ+UZsGUt/P1wG8E5RzbiKMowsb4nAO6bqgjH/qJnQDjPUTfhysQYyQ37nDiFljLLd/fRgz3JfnDb1TTzvGOGEfRshv87QcC3XavLnMrV0HmhAdL1dSzjFO9VZzlXrfdAKSb2mdJf/YdAc8Uxu2ErPe062XQ2/8S+Byr8QSt5Mhz8mPfcJFr6CKCeMIil+FIe9/P5nEj2oLzfeK0M0W+/muCPxC23c6K9DpIjns5ks+mw6b6NGIBXn0t3zDzQTXAaZLA8q2BkGcCXEztpKSA5tO8CrwaX1mn2vdbsomvggVzGpqkacgcmcFEGmNUHf3Oz5Vud5FIzLB9rQzw8rDi98xltwRZlWEcxxTLB1eBjul4MZ4iifqk="
  - secure: rGfMLzq9B0pSykGZsgGKr+OTxJTPqlJLziLxM5ZnvJtxb/pNiVg1c84D24VCUKEsDiPLRx67B2ab/4IISBNWtw8v67GbEjG186cBwQJoUoK2qlav0iE/IDpmObn8P5zzNCpXD8RUxy7fsCo8myqJ7DSmA1tBsIfrkUhss1/fJK2bjAHdgmDYciQ78dewgKM2uUovoZMi7DTlmqEtmVGMqG4I4/pQKjCvSy6rKW8IfXfIONX9XvzH7ijs2Tu7QY0xeDhJElfWIwGeOOlqBMSEWT1euXW19Zyd8FIRrRk2A63mr/ls68hc5yotCG7Vs27PwGNLztnz3+wkG2t7UC+urs3ITn2ppi4cOmgRTP3bejFNVyzKfid3yFcNVNPjPRLlaEmduczLlQi4CWZW7Ne+l+Ho8s3c8ghZZ0hTtQOXEJqgso6lx016fqD8sj4Wb8POWJgGtnmHhIj+MlR9OIMdyJmPNe2ib2QBm4QqIVUQDDWubtqjgbmApWRsG47DiO7qoKz8CNzTtKFc5eCmlGCEtsKeEAIRe1yifhCPPr4d9sdEz27uMf2xIspiJHXrkMTcL3S1mZ7vH+9c8CTYZ3aONymEn6IY0eNDgFCSAf7hwByMFqnlkX0uWLxkGQmK+CCqw3Sgbt2rar5hwKE/Cez6uzBDr6iMOSL3BCK9lE4neJc=
