language: node_js
install: npm install
node_js:
- 'node'
- '6'
before_install:
- if [[ `npm -v` = 3* ]]; then npm i -g npm@5; fi
before_script:
- npm ls
sudo: 'false'
addons:
  chrome: stable
script: npm run lint && npm run build && npm run test
jobs:
  include:
    - stage: test
      name: "End 2 end tests"
      script: npm run build && npm run e2e
    - stage: Performance test
      name: "npm run perf"
      script: npm run build && npm run perf
    - stage: release
      script: npm run build && ".travis/ci-release.jsh"
      env:
        - secure: YS5/OoRepciTMeHa9U5AV77yI2PLu+qpNDc5K+S2thRG90uDx4ePL0w6fbKs4olwE152zVieKfBrm7Q/kpcYp97IdDSryWzDyvFMa3u3/2BlA2d3zoyj06+5qH7dFHMUA8X1eix6RtcDYkKgT0++Y4Uprtl6bjSSeiaA3K97eCDXYQHrsr2ChjSgHCOrz7qpUVZER6BhVbFXbJkl+uJohs/e5wfGNfpOZTmMnWC1E3I4ev4JL0kfk1JObo0r45pitCnwgiSFGvrBpbPgcLYR/dTUJeuDKiR7oQNwWto1kxAJ8RH79wwrSNV9FN2USMnH+Eb39hyauyYz2DlYMJJ6KX6RXqUpXHFqGKfOovMb2sseepJT6EVC/Phjo5E7G7dgv1MAi8XcEztKWqKaxYSgeFYhUw5vZufdpnMhr/+bE7SaDgscKgxnnt2hlJ/KwR3gBFhspykuY7qA8WDCTYo2mswy0GTBfLOn2aC6P3cSKUrCwTuzZcaYFSIIIP26t9Sgj9JGcQ+kY/YIELBIEbOly7Ydf8jeM4DEsLClOriTbMVbA5TTao9HBSmIEK4WxN1Jh5SM67PNOhNNbLp69kUh/cZ0g68ORfCRESt69SEu8z3myumw+rpdjxF9SdzTp24Xh2HFF7XOg4/ZNmWXh7jjp1tZ7NzMaUmWt3WuBc6fZOo=
        - secure: EhfzUfITtwsAir3v0qlWYnmCl43tbEGwM9aBwz3sDYARW8vzlsN5o4uuCkpVoE8vRuCTc8Bwg2BvCWglt6HEZx0Vspp83JuiKhRnbIAQcHQWGqpTS76ml6H62kESOQoNEMMBCmi53w3t+N2f5epVugz4GGtx9SNpoLXLNK3q32WVEZY6uPsKzksdF/F878/c7ty+9DxFNd4/ja1rTMmhkLis4IoaWZsDteazCKLzL11KXwNjUzEOXEcUFSTh+cQs4iKxuAsZWPF9y0ks6Cd9mvvUwoAG3qvsLhCzqQMw7CeavKtw+GMG2v7w3ypzhoIBaB+9rjUagyidkkfFFxe3t/Gl/VnbDp9y4gfEqxCGMQeL+lIG9Msemb3T9GT3ibwAOmkYQ0HTWGyUsXAhpceo0U3Gb1GKTmqsC1gPFI+L0H/mv5mN4SVjF0myi6wgHJm1XKKa8//86O0GPJ81SiPgxes2WZYUEf80rjzdGPVMnkclKvtyTrlxsqsYvLFJ3c8dJbk9LAdvnDpNaJpRTZ6U9dqC6YSkIGJHn0jhIO7WXv5RZjS5QApJqDsl3vFQDoUU2ZK54wFV90CjPUfk4HedYpCJ91FbV0g5Gd6kRGDRp1jGOZfYYk4/Ie7LZ27RbNIKYaJTKzBZR8sPyyanP6/iY8vVLMv6q8GOLv10OLUdImA=
branches:
  only:
  - master
  - release
  - v1

# Conditional stages: https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
stages:
  - test
  - name: release
    if: branch = release AND fork = false
  - name: "Performance test"
    if: type = cron # Only run in nightly build
