name: CI

on:
  pull_request: ~
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 24.x]
        os: ['ubuntu-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/setup
        with:
          node-version: ${{ matrix.node-version }}
          install-deps: false
      - name: Install dependencies
        run: pnpm install --filter "./packages/**" --frozen-lockfile && pnpm run install:chromium
      - name: Build & lint & test
        run: pnpm run all

  incremental_mutation_test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/setup
      - name: Build
        run: pnpm run build:no-check
      - name: Download incremental reports
        run: pnpm run download-incremental-reports
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      - name: Run stryker run --incremental
        run: pnpm run test:mutation:incremental --dashboard.version ${{ github.head_ref || github.ref_name }}
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/setup
        with:
          node-version: 22.x
      # https://github.com/ryanclark/karma-webpack/issues/494
      - name: Windows temp dir fix
        run: |
          echo TEMP="D:\Temp" >> $env:GITHUB_ENV
          echo TMP="D:\Temp" >> $env:GITHUB_ENV
      - name: Build packages
        run: pnpm run build:no-check
      - name: install build output
        run: 'pnpm install --frozen-lockfile'
      - name: e2e lint
        run: 'pnpm run e2e:lint'
      - name: Run e2e tests
        run: 'pnpm run e2e:run'
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: e2e-reports
          path: |
            e2e/test/*/reports/mutation/
            e2e/test/*/stryker.log
