name: CI

on:
  pull_request: ~
  merge_group:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci --engine-strict
    - name: Build & lint & test
      run: npm run all
  
  incremental_mutation_test:
      runs-on: 'ubuntu-latest'
      steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:no-check
      - name: Download incremental reports
        run: npm run download-incremental-reports
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      - name: Run stryker run --incremental
        run: npm run test:mutation:incremental
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    # https://github.com/ryanclark/karma-webpack/issues/494
    - name: Windows temp dir fix
      run: |
        echo TEMP="D:\Temp" >> $env:GITHUB_ENV
        echo TMP="D:\Temp" >> $env:GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Install dependencies
      # retry once, install on windows is flaky...
      run: npm ci || npm ci
    - name: Build packages
      run: npm run build:no-check
    - name: e2e install
      run: 'npm run e2e:install'
    - name: e2e lint
      run: 'npm run e2e:lint'
    - name: Run e2e tests
      run: 'npm run e2e:run'
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-reports
        path: |
          e2e/test/*/reports/mutation/
          e2e/test/*/stryker.log