name: Performance

on:
  workflow_dispatch:
    inputs:
      PERF_TEST_GLOB_PATTERN:
        description: 'Glob pattern'
        required: true
        default: '*'

jobs:
  performance_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install && node --run install:chromium
      - name: Build packages
        run: node --run build
      - name: Run performance tests
        run: node --run perf
        env:
          PERF_TEST_GLOB_PATTERN: ${{ github.event.inputs.PERF_TEST_GLOB_PATTERN }}
      - name: Store reports
        uses: actions/upload-artifact@v4
        with:
          name: mutation-testing-reports
          path: perf/test/*/reports/mutation
